const palette = {
  sage: "#2D3E50",
  sageDark: "#1E2D3D",
  sageLight: "#F2F7EC",
  sageMuted: "#C8D8C4",
  navy: "#1A2836",
  navyLight: "#2D3E50",
  slate: "#5A6B7A",
  slateLight: "#8A9BAA",
  warm: "#D4A574",
  warmLight: "#FFF5EC",
  coral: "#C85A54",
  coralLight: "#FEF2F0",
  sky: "#4A8BA8",
  skyLight: "#E8F3F8",
  surface: "#F5F8F2",
  surfaceCard: "#FFFFFF",
  border: "#D8E0D4",
  borderLight: "#EBF0E6",
  textPrimary: "#1A2836",
  textSecondary: "#4A5B6A",
  textMuted: "#8A9BAA",
  white: "#FFFFFF",
  black: "#000000",
  success: "#4A8B6A",
  successLight: "#EDF5F0",
};

export default {
  light: {
    text: palette.textPrimary,
    textSecondary: palette.textSecondary,
    textMuted: palette.textMuted,
    background: palette.surface,
    tint: palette.sage,
    tintDark: palette.sageDark,
    tintLight: palette.sageLight,
    tintMuted: palette.sageMuted,
    tabIconDefault: palette.slateLight,
    tabIconSelected: palette.sage,
    card: palette.surfaceCard,
    border: palette.border,
    borderLight: palette.borderLight,
    accent: palette.warm,
    accentLight: palette.warmLight,
    danger: palette.coral,
    dangerLight: palette.coralLight,
    info: palette.sky,
    infoLight: palette.skyLight,
    success: palette.success,
    successLight: palette.successLight,
    navy: palette.navy,
    navyLight: palette.navyLight,
    slate: palette.slate,
    slateLight: palette.slateLight,
    white: palette.white,
    black: palette.black,
  },
};
