const palette = {
  sage: "#2E5E3F",
  sageDark: "#1F4A2E",
  sageLight: "#E8F0E4",
  sageMuted: "#8DB89A",
  navy: "#1F4A2E",
  navyLight: "#2E5E3F",
  slate: "#4A6B5A",
  slateLight: "#7A9B8A",
  warm: "#D4A574",
  warmLight: "#FFF5EC",
  coral: "#C85A54",
  coralLight: "#FEF2F0",
  sky: "#4A8BA8",
  skyLight: "#E8F3F8",
  surface: "#F4F9F2",
  surfaceCard: "#FFFFFF",
  border: "#B8CCBA",
  borderLight: "#C8DCC6",
  textPrimary: "#1A3328",
  textSecondary: "#3A5C48",
  textMuted: "#7A9B8A",
  white: "#FFFFFF",
  black: "#000000",
  success: "#3A7A52",
  successLight: "#E0F0E4",
};

export default {
  light: {
    text: palette.textPrimary,
    textSecondary: palette.textSecondary,
    textMuted: palette.textMuted,
    background: palette.surface,
    tint: palette.sage,
    tintDark: palette.sageDark,
    tintLight: palette.sageLight,
    tintMuted: palette.sageMuted,
    tabIconDefault: palette.slateLight,
    tabIconSelected: palette.sage,
    card: palette.surfaceCard,
    border: palette.border,
    borderLight: palette.borderLight,
    accent: palette.warm,
    accentLight: palette.warmLight,
    danger: palette.coral,
    dangerLight: palette.coralLight,
    info: palette.sky,
    infoLight: palette.skyLight,
    success: palette.success,
    successLight: palette.successLight,
    navy: palette.navy,
    navyLight: palette.navyLight,
    slate: palette.slate,
    slateLight: palette.slateLight,
    white: palette.white,
    black: palette.black,
  },
};
