const palette = {
  emerald: "#0D9373",
  emeraldDark: "#087A60",
  emeraldLight: "#E8F7F3",
  emeraldMuted: "#B8E6D8",
  navy: "#0F1B2D",
  navyLight: "#1A2B42",
  slate: "#64748B",
  slateLight: "#94A3B8",
  warm: "#F97316",
  warmLight: "#FFF1E6",
  coral: "#EF4444",
  coralLight: "#FEF2F2",
  sky: "#0EA5E9",
  skyLight: "#E0F2FE",
  surface: "#F8FAFB",
  surfaceCard: "#FFFFFF",
  border: "#E2E8F0",
  borderLight: "#F1F5F9",
  textPrimary: "#0F172A",
  textSecondary: "#475569",
  textMuted: "#94A3B8",
  white: "#FFFFFF",
  black: "#000000",
  success: "#10B981",
  successLight: "#ECFDF5",
};

export default {
  light: {
    text: palette.textPrimary,
    textSecondary: palette.textSecondary,
    textMuted: palette.textMuted,
    background: palette.surface,
    tint: palette.emerald,
    tintDark: palette.emeraldDark,
    tintLight: palette.emeraldLight,
    tintMuted: palette.emeraldMuted,
    tabIconDefault: palette.slateLight,
    tabIconSelected: palette.emerald,
    card: palette.surfaceCard,
    border: palette.border,
    borderLight: palette.borderLight,
    accent: palette.warm,
    accentLight: palette.warmLight,
    danger: palette.coral,
    dangerLight: palette.coralLight,
    info: palette.sky,
    infoLight: palette.skyLight,
    success: palette.success,
    successLight: palette.successLight,
    navy: palette.navy,
    navyLight: palette.navyLight,
    slate: palette.slate,
    slateLight: palette.slateLight,
    white: palette.white,
    black: palette.black,
  },
};
